In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
df = pd.read_pickle("data/df.pkl")
df.head()

,description,popularity,poster_path,vote_average,vote_count,tmdb_id,movieId,title,year,Adventure,...,Musical,Western,Film-Noir,tmdbId,actor1,actor2,actor3,actor4,actor5,director1
1846,"In the rail yards of Queens, contractors repai...",8.673,/AtwXtU8CDWvVADgOwRkOSRZFPWI.jpg,6.187,347.0,19457.0,2769,"Yards, The",2000,0,...,0,0,0,19457,Mark Wahlberg,Joaquin Phoenix,Charlize Theron,James Caan,Ellen Burstyn,James Gray
1341,A streetwise man flees South Central Los Angel...,15.079,/dP4fYCGQZzg17ta7FvLwJVCwwt9.jpg,6.412,453.0,10471.0,3177,Next Friday,2000,0,...,0,0,0,10471,Ice Cube,Mike Epps,Justin Pierce,John Witherspoon,Don Curry,Steve Carr
1342,"Set in the 22nd century, when a battered salva...",10.531,/AmHGUjhgXnOYRYrF2ZYMtzfwxPe.jpg,4.957,299.0,10384.0,3190,Supernova,2000,1,...,0,0,0,10384,James Spader,Angela Bassett,Robert Forster,Lou Diamond Phillips,Peter Facinelli,Walter Hill
1840,"College coeds in New York City, Al, the son of...",10.192,/ptvHDZtJxj9kj1unae6ryoXsmud.jpg,5.200,205.0,10472.0,3225,Down to You,2000,0,...,0,0,0,10472,Freddie Prinze Jr.,Julia Stiles,Selma Blair,Shawn Hatosy,Zak Orth,Kris Isacsson
23239,"On the eve of his wedding, a Manhattanite take...",1.326,/4G8TwEngXbAnuLKQvOZ2qbODnh5.jpg,4.300,3.0,97805.0,3228,Wirey Spindell,2000,0,...,0,0,0,97805,Eric Schaeffer,Eric Mabius,Callie Thorne,Peggy Gormley,Gideon Jacobs,Eric Schaeffer

In [22]:
list(df.popularity.sort_values(ascending=False))[10001]

6.654

In [28]:
df[df.popularity >= list(df.popularity.sort_values(ascending=False))[10000]].index

Int64Index([ 1846,  1341,  1342,  1840,  1248,   789,  7778,    86,  1343,
             3306,
            ...
            31218, 19174, 29514, 15676, 19768, 20874, 30233, 29515,  8655,
            29677],
           dtype='int64', length=10001)